name: '[docker] CI for releases to ghcr'

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
      - '.github/workflows/docker-release.yml'
      - 'Dockerfile'
      - 'package.json'
      - 'yarn.lock'
  workflow_dispatch: ~

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ghcr.io/kbc8894/rsshub:latest
            ghcr.io/kbc8894/rsshub:${{ steps.short-sha.outputs.sha }}

